version: '3.1'
services:
  db:
    image: mysql
    container_name: bangtanPalace
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - springCourse:/var/lib/mysql

volumes:
  springCourse: